# netlify.toml – קובץ קונפיג לשורש הריפו (לא בתוך frontend)
[build]
  base    = "frontend"
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"
